//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConnecter.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityConnecter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   D_MA_USR_FAV_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string D_MA_USR_FAV_SIN {
            get {
                return ResourceManager.GetString("D_MA_USR_FAV_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_MA_USR_FAV_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I_MA_USR_FAV_SIN {
            get {
                return ResourceManager.GetString("I_MA_USR_FAV_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_MA_USR_PRCH_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I_MA_USR_PRCH_SIN {
            get {
                return ResourceManager.GetString("I_MA_USR_PRCH_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_MA_USR_REV_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I_MA_USR_REV_SIN {
            get {
                return ResourceManager.GetString("I_MA_USR_REV_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestConnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QUERY_02 {
            get {
                return ResourceManager.GetString("QUERY_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_CO_ETC_VER_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_CO_ETC_VER_SIN {
            get {
                return ResourceManager.GetString("S_CO_ETC_VER_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_CO_USR_LGN_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_CO_USR_LGN_SIN {
            get {
                return ResourceManager.GetString("S_CO_USR_LGN_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_CV_CTS_INFO_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_CV_CTS_INFO_SIN {
            get {
                return ResourceManager.GetString("S_CV_CTS_INFO_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_CV_CTS_REV_LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_CV_CTS_REV_LIST {
            get {
                return ResourceManager.GetString("S_CV_CTS_REV_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_MA_CTS_SRCH_LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_MA_CTS_SRCH_LIST {
            get {
                return ResourceManager.GetString("S_MA_CTS_SRCH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_MA_USR_FAV_LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_MA_USR_FAV_LIST {
            get {
                return ResourceManager.GetString("S_MA_USR_FAV_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_MA_USR_PRCH_LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_MA_USR_PRCH_LIST {
            get {
                return ResourceManager.GetString("S_MA_USR_PRCH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_MA_USR_REV_LIST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S_MA_USR_REV_LIST {
            get {
                return ResourceManager.GetString("S_MA_USR_REV_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U_MA_USR_REV_SIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U_MA_USR_REV_SIN {
            get {
                return ResourceManager.GetString("U_MA_USR_REV_SIN", resourceCulture);
            }
        }
    }
}
